#pragma once

#define MAX_BOXES 23
#define MAX_BUTTONS 84
#define MAX_SIZERS 1
#define MAX_MOVERS 8
#define MAX_SCROLLERS 14
#define MAX_CHECKBOXES 1
#define MAX_CHARSCREENTEXT 4
#define MAX_CREATEACCOUNTINFO 6
#define MAX_EDITACCOUNTINFO 4
#define MAX_PRIMARYACTIONS 15
#define MAX_SECONDARYACTIONS 11
#define MAX_ACTIONS MAX_PRIMARYACTIONS + MAX_SECONDARYACTIONS

#define GAMESTATE_INITIALIZE 1
#define GAMESTATE_LOGO 2
#define GAMESTATE_STARTSCREEN 3
#define GAMESTATE_STARTCHARSCREEN 4
#define GAMESTATE_RETURNSTARTSCREEN 5
#define GAMESTATE_QUIT 6
#define GAMESTATE_CHARSCREEN 7
#define GAMESTATE_STARTCONNECTION 8
#define GAMESTATE_CONNECTING 9
#define GAMESTATE_STARTGAME 10
#define GAMESTATE_INGAME 11
#define GAMESTATE_STARTCAMPAIGN 12
#define GAMESTATE_INGAMECAMPAIGN 13
#define GAMESTATE_CREDITS 14
#define GAMESTATE_GAMEOVER 15
#define GAMESTATE_CONTINUECAMPAIGN 16
#define GAMESTATE_QUITCAMPAIGN 17

enum QueryFlags
{
	OBJECT_MASK = 1 << 0,
	UNIT_MASK = 1 << 1,
	SKY_MASK = 1 << 2,
	WORLDOBJECT_MASK = 1 << 3,
	EFFECT_MASK = 1 << 4,
	ITEM_MASK = 1 << 5,
	CRITTER_MASK = 1 << 6
};
